apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic-hq
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
     component: elastic-hq
  template:
    metadata:
      labels:
        component: elastic-hq
    spec:
      containers:
      - name: elastic-hq
        image: elastichq/elasticsearch-hq
        ports:
        - containerPort: 5000
          name: http

---
apiVersion: v1
kind: Service
metadata:
  name: elastic-hq-cs
  namespace: logging
  labels:
    component: elastic-hq
spec:
  selector:
    component: elastic-hq
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 5000
    name: elastic-hq-5000
  type: ClusterIP