apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-lb
  namespace: logging
  labels:
    app: elasticsearch-master
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  selector:
    app: elasticsearch-master
  ports:
  - protocol: "TCP"
    port: 9200
    targetPort: 9200
    name: elasticsearch-9200
  - protocol: "TCP"
    port: 9300
    targetPort: 9300
    name: elasticsearch-9300
  type: LoadBalancer
