apiVersion: apps/v1
kind: Deployment
metadata:
  name: aiservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aiservice
  template:
    metadata:
      labels:
        app: aiservice
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: aiservice
        image: 777205220558.dkr.ecr.ap-northeast-2.amazonaws.com/aiservice
        command: ["uvicorn"]
        args: ["main:app", "--reload", "--port", "8089"] 
        ports:
          - containerPort: 8089
            name: http
        volumeMounts:
        - name: ai-model
          mountPath: /model/
      volumes:
        - name: ai-model
          persistentVolumeClaim:
            claimName: ai-model-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: aiservice-cs
  labels:
    app: aiservice
    service: aiservice
spec:
  ports:
  - port: 8089
    targetPort: 8089
    name: http
  selector:
    app: aiservice
  type: ClusterIP
