apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
  labels:  # ✅ 반드시 metadata 아래!
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
type: Opaque
data:
  admin.password: ${ARGO_ACC_PASS}
  admin.passwordMtime: ${ARGO_ACC_DATE}