apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
labels:
  app.kubernetes.io/name: argocd-secret
  app.kubernetes.io/part-of: argocd
type: Opaque
data:
  admin.password: ${{ secrets.ARGO_ACC_PASS}}
  admin.passwordMtime: ${{ secrets.ARGO_ACC_DATE}}