apiVersion: apps/v1
kind: Deployment
metadata:
  name: congestion-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: congestion-service
  template:
    metadata:
      labels:
        app: congestion-service
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: congestion-service
          image: 777205220558.dkr.ecr.ap-northeast-2.amazonaws.com/congestion-service
          command: ["java"]
          #        args: ["-Dspring.profiles.active=dev","-jar","/demo1.jar"]
          args: ["-Dspring.profiles.active=dev","-Dspring.config.location=/classes/application.properties","-jar","/app/congestion.jar"]
          ports:
            - containerPort: 8081
              name: http
          volumeMounts:
            - name: config
              mountPath: /classes/
      volumes:
        - name: config
          configMap:
            name: congestion-config
#            items: # 콘피그 맵 중에서 하나만 뽑아서 파일로 저장할때는 item 사용
#              - key: "application.properties"
#                path: "application.properties"
            # 아이템 없으면 콘피그맵에 있는 모든 파일이 해당 경로에 생성된다.

---
apiVersion: v1
kind: Service
metadata:
  name: congestion-service-cs
  labels:
    app: congestion-service
    service: congestion-service
spec:
  ports:
    - port: 8081
      name: http
  selector:
    app: congestion-service
  type: ClusterIP
