apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: gateway
          image: 777205220558.dkr.ecr.ap-northeast-2.amazonaws.com/gateway
          command: ["java"]
          #        args: ["-Dspring.profiles.active=dev","-jar","/demo1.jar"]
          args: [ "-Dspring.profiles.active=dev",
                  "-Dspring.config.location=/classes/application.properties",
                  "-Dlogging.config=/classes/logback-spring.xml", # 이거는 스프링에 logstash 의존성 없으면 에러 뜸
                  "-jar",
                  "/app/gateway.jar" ]
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: config
              mountPath: /classes/application.properties
              subPath: application.properties
            - name: logging
              mountPath: /classes/logback-spring.xml
              subPath: logback-spring.xml
      volumes:
        - name: config
          configMap:
            name: gateway-config
            items:
              - key: "application.properties"
                path: "application.properties"

        - name: logging
          configMap:
            name: gateway-config
            items:
              - key: "logback-spring.xml"
                path: "logback-spring.xml"

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-cs
  namespace: backend
  labels:
    app: gateway
    service: gateway
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: gateway
  type: ClusterIP
