---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gateway
  name: gateway-lb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: gateway
  selector:
    app: gateway
  type: LoadBalancer
