apiVersion: apps/v1
kind: Deployment
metadata:
  name: place-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: place-service
  template:
    metadata:
      labels:
        app: place-service
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: place-service
          image: 777205220558.dkr.ecr.ap-northeast-2.amazonaws.com/place-service
          command: ["java"]
          #        args: ["-Dspring.profiles.active=dev","-jar","/demo1.jar"]
          args: [ "-Dspring.profiles.active=dev",
                  "-Dspring.config.location=/classes/application.properties",
                  "-Dlogging.config=/classes/logback-spring.xml", # 이거는 스프링에 logstash 의존성 없으면 에러 뜸
                  "-jar",
                  "/app/place.jar" ]
          ports:
            - containerPort: 8082
              name: http
          readinessProbe: # 헬스체크 해서 이거가 되면 파드 실행
            httpGet:
              path: /swagger-ui/index.html
              port: 8082
            periodSeconds: 5
            timeoutSeconds: 5
          volumeMounts:
            - name: config
              mountPath: /classes/application.properties
              subPath: application.properties
            - name: logging
              mountPath: /classes/logback-spring.xml
              subPath: logback-spring.xml
      volumes:
        - name: config
          configMap:
            name: place-config
            items:
              - key: "application.properties"
                path: "application.properties"

        - name: logging
          configMap:
            name: place-config
            items:
              - key: "logback-spring.xml"
                path: "logback-spring.xml"


---
apiVersion: v1
kind: Service
metadata:
  name: place-service-cs
  labels:
    app: place-service
    service: place-service
spec:
  ports:
    - port: 8082
      name: http
  selector:
    app: place-service
  type: ClusterIP
