apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: user-service
          image: 777205220558.dkr.ecr.ap-northeast-2.amazonaws.com/user-service
          command: ["java"]
          #        args: ["-Dspring.profiles.active=dev","-jar","/demo1.jar"]
          # D머시기 애들은 자바 실행할 때 설정 파일들 경로 지정해서 그 파일로 설정할거다 말해주는 거임
          args: ["-Dspring.profiles.active=dev",
                 "-Dspring.config.location=/classes/application.properties",
                 "-Dlogging.config=/classes/logback-spring.xml",
                 "-jar",
                 "/app/user.jar"]
          ports:
            - containerPort: 8083
              name: http
          readinessProbe: # 헬스체크 해서 이거가 되면 파드 실행
            httpGet:
              path: /swagger-ui/index.html
              port: 8083
            periodSeconds: 30
            timeoutSeconds: 30
          volumeMounts:
            - name: config
              mountPath: /classes/application.properties
              subPath: application.properties
            - name: logging
              mountPath: /classes/logback-spring.xml
              subPath: logback-spring.xml

      volumes:
        - name: config
          configMap:
            name: user-config
            items:
              - key: "application.properties"
                path: "application.properties"
        - name: logging
          configMap:
            name: user-config
            items:
              - key: "logback-spring.xml"
                path: "logback-spring.xml"


---
apiVersion: v1
kind: Service
metadata:
  name: user-service-cs
  labels:
    app: user-service
    service: user-service
spec:
  ports:
    - port: 8083
      name: http
  selector:
    app: user-service
  type: ClusterIP
