apiVersion: v1
kind: Service
metadata:
  name: jenkins-lb
  namespace: jenkins
  labels:
    app: jenkins
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  selector:
    app: jenkins
  ports:
  - protocol: "TCP"
    port: 8888
    targetPort: 8080
    nodePort: 32000
    name: jenkins-dev-80
  type: LoadBalancer

