repoServer:
  volumeMounts:
    - mountPath: /tmp
      name: tmp-dir  # MUST match existing name in chart
  volumes:
    - name: tmp-dir
      persistentVolumeClaim:
        claimName: argocd-repo-server-pvc

applicationController:
  volumeMounts:
    - mountPath: /shared-data
      name: controller-data
  volumes:
    - name: controller-data
      persistentVolumeClaim:
        claimName: argocd-application-controller-pvc

server:
  volumeMounts:
    - mountPath: /home/argocd
      name: static-files   # ← ArgoCD 기본 이름과 동일해야 함!
  volumes:
    - name: static-files
      persistentVolumeClaim:
        claimName: argocd-server-pvc
