apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash-oss:6.8.23
          ports:
            - containerPort: 5000
          imagePullPolicy: IfNotPresent # Always, Never
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/logstash/config/logstash.yml
              subPath: logstash.yml

            - name: logstash-pipeline-volume
              mountPath: /usr/share/logstash/pipeline/logstash.conf
              subPath: logstash.conf

            - name: logstash-pipeline-yml # logstash는 config 폴더에 pipelines.yml이 존재해야 함
              mountPath: /usr/share/logstash/config/pipelines.yml
              subPath: pipelines.yml

#            - name: tz-seoul 시간 설정을 서울로 하는건데 추후 추가
#              mountPath: /etc/localtime
      volumes:
#        - name: tz-seoul
#          hostPath:
#            path: /usr/share/zoneinfo/Asia/Seoul
        - name: config-volume
          configMap:
            name: logstash-config
            items:
              - key: logstash.yml
                path: logstash.yml
        - name: logstash-pipeline-volume
          configMap:
            name: logstash-config
            items:
              - key: logstash.conf
                path: logstash.conf

        - name: logstash-pipeline-yml
          configMap:
            name: logstash-config
            items:
              - key: pipelines.yml
                path: pipelines.yml

---
apiVersion: v1
kind: Service
metadata:
  name: logstash-cs
  namespace: logging
  labels:
    app: logstash
    service: logstash
spec:
  ports:
    - name: tcp
      port: 5000
      targetPort: 5044

  selector: # 아래의 라벨을 가진 파드들에게 트래픽을 보낼거임
    # 파드가 여러개일 경우 기본적으로 라운드로빈 방식으로 하나씩 트래픽을 보냄
    app: logstash
  type: ClusterIP # 클러스터에서만 접근 가능한 IP로 서비스를 배포할 것이다.
