kind: ConfigMap
apiVersion: v1
metadata:
  name: zipkin-test-config
data:
  application.yml: |-
    spring:
      application:
        name: demo1
      kafka:
        bootstrap-servers: kafka-svc:9093
        template:
          default-topic: base-event
        consumer:
          group-id: demo1-group

    management:
      tracing:
        enabled: true
        sampling:
          probability: 1.0

      zipkin:
        tracing:
          enabled: true
          endpoint: http://zipkin:9411/api/v2/spans
    logging:
      pattern:
        level: "%5p [${spring.application.name:},%X{traceId},%X{spanId}]"
      level:
        root: INFO
