---
apiVersion: v1
kind: Service
metadata:
  labels:
    component: redis-master
  name: redis-master-lb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    component: redis-master
  type: LoadBalancer
