apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datacollector
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/heozzi/Cloud-STARS
    targetRevision: HEAD
    path: datacollector
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
