apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: efs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/heozzi/Cloud-STARS
    targetRevision: HEAD
    path: efs
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
